### ISSUE TITLE
Versioning is tough to follow

### ISSUE THREAD

**Issue by ejc123** [JetBrains/sbt-ide-settings#1]
Readme.md suggests using "<version>", but does not list versions.  I checked out the bintray repo, but the versions there are listed in alphabetical instead of chronological order and do not list timestamp (at leas in the browser).

I recommend either a list of versions, or a link to the most current version.

**Comment by dancingrobot84** [comment]
Hi! I've merged corresponding changes from @howyp. Btw, available versions are listed [here](https://github.com/JetBrains/sbt-ide-settings/releases).
