### ISSUE TITLE
Publish with SBT 1.9

### ISSUE THREAD

**Issue by ScalaWilliam** [JetBrains/sbt-ide-settings#16]
Hi! I noticed [update sbt to 1.9.1](https://github.com/JetBrains/sbt-ide-settings/commit/667696d313f8499c70277cf159622884053bd942) was already done, but no release was made - any chance this could happen? The latest is 1.1 but from before this Git commit. Would be hugely appreciated!

**Comment by vasilmkd** [comment]
Of course. Any other plugins that you need/would like to see re-published? We usually publish them only when we need a new version to change some behavior.

**Comment by ScalaWilliam** [comment]
So far this was the only one that was left blocked. It's a little difficult to pin-point (I had to publish this one locally by hand to make the rest of the process work) as the plugins are mostly a chain reaction sort of thing.

**Comment by vasilmkd** [comment]
There is this snapshot version `1.1.1+1-667696d3-SNAPSHOT`. I suppose you can already resolve it from the snapshots repository.

I will properly update the plugin tomorrow at work. It requires reviving the publishing process and is something I cannot do at the moment.

**Comment by vasilmkd** [comment]
Published 1.1.2.

https://repo1.maven.org/maven2/org/jetbrains/scala/sbt-ide-settings_2.12_1.0/1.1.2/
