### ISSUE TITLE
coordinate with ensime on shared keys

### ISSUE THREAD

**Issue by jastice** [JetBrains/sbt-ide-settings#9]
ensime supports a number of sbt config keys specific to ensime import. Several of these would also be a good addition for IntelliJ import.

see https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L23-L124

cc @fommil

**Comment by SethTisue** [comment]
ENSIME (the old one) is no longer active, so this could probably be closed?

**Comment by jastice** [comment]
yup, thanks!

**Comment by fommil** [comment]
there might be some ENSIME:TOS movies, but for sure the TV show is just going to be TNG from now on.

Let's hope there is no Voyager.
